import { create } from 'zustand';
import { Farmer, Transporter, Store, Vehicle, MarketplaceListing, TransportRequest } from '../types';

interface DemoDataState {
  farmers: Farmer[];
  transporters: Transporter[];
  stores: Store[];
  vehicles: Vehicle[];
  marketplaceListings: MarketplaceListing[];
  transportRequests: TransportRequest[];
}

// Demo Farmers Data
const demoFarmers: Farmer[] = [
  {
    id: 'farmer-1',
    name: 'Ahmed Ben Ali',
    email: 'ahmed.benali@farm.ma',
    role: 'farmer',
    avatar: 'https://i.pravatar.cc/150?img=1',
    phoneNumber: '+212601020304',
    address: 'Douar Oulad Mansour, Marrakech',
    createdAt: new Date('2023-01-15'),
    farmName: 'Green Valley Farms',
    farmLocation: {
      latitude: 31.6295,
      longitude: -7.9811,
      address: 'Douar Oulad Mansour, Marrakech',
    },
    cropTypes: ['Olives', 'Oranges', 'Tomatoes', 'Mint'],
    ratings: 4.7,
  },
  {
    id: 'farmer-2',
    name: 'Fatima Zahra',
    email: 'fatima.zahra@farm.ma',
    role: 'farmer',
    avatar: 'https://i.pravatar.cc/150?img=5',
    phoneNumber: '+212602030405',
    address: 'Commune Sidi Rahal, Casablanca',
    createdAt: new Date('2023-02-10'),
    farmName: 'Atlas Organic Farm',
    farmLocation: {
      latitude: 33.3823,
      longitude: -7.6094,
      address: 'Commune Sidi Rahal, Casablanca',
    },
    cropTypes: ['Strawberries', 'Lettuce', 'Carrots', 'Herbs'],
    ratings: 4.9,
  },
  {
    id: 'farmer-3',
    name: 'Youssef Alami',
    email: 'youssef.alami@farm.ma',
    role: 'farmer',
    avatar: 'https://i.pravatar.cc/150?img=3',
    phoneNumber: '+212603040506',
    address: 'Ouled Teima, Taroudant',
    createdAt: new Date('2023-03-05'),
    farmName: 'Souss Valley Citrus',
    farmLocation: {
      latitude: 30.3910,
      longitude: -9.2076,
      address: 'Ouled Teima, Taroudant',
    },
    cropTypes: ['Oranges', 'Lemons', 'Grapefruits', 'Clementines'],
    ratings: 4.6,
  },
  {
    id: 'farmer-4',
    name: 'Khadija Bennani',
    email: 'khadija.bennani@farm.ma',
    role: 'farmer',
    avatar: 'https://i.pravatar.cc/150?img=9',
    phoneNumber: '+212604050607',
    address: 'Ain Taoujdate, Fes',
    createdAt: new Date('2023-01-20'),
    farmName: 'Middle Atlas Vegetables',
    farmLocation: {
      latitude: 33.9716,
      longitude: -5.0033,
      address: 'Ain Taoujdate, Fes',
    },
    cropTypes: ['Potatoes', 'Onions', 'Beans', 'Peas'],
    ratings: 4.5,
  },
  {
    id: 'farmer-5',
    name: 'Omar Idrissi',
    email: 'omar.idrissi@farm.ma',
    role: 'farmer',
    avatar: 'https://i.pravatar.cc/150?img=7',
    phoneNumber: '+212605060708',
    address: 'Berkane, Oriental',
    createdAt: new Date('2023-04-12'),
    farmName: 'Oriental Fruits Co.',
    farmLocation: {
      latitude: 34.9218,
      longitude: -2.3218,
      address: 'Berkane, Oriental',
    },
    cropTypes: ['Clementines', 'Olives', 'Almonds', 'Grapes'],
    ratings: 4.8,
  },
  {
    id: 'farmer-6',
    name: 'Aicha Tazi',
    email: 'aicha.tazi@farm.ma',
    role: 'farmer',
    avatar: 'https://i.pravatar.cc/150?img=11',
    phoneNumber: '+212606070809',
    address: 'Larache, Tangier-Tetouan',
    createdAt: new Date('2023-02-28'),
    farmName: 'Atlantic Coast Farm',
    farmLocation: {
      latitude: 35.1932,
      longitude: -6.1563,
      address: 'Larache, Tangier-Tetouan',
    },
    cropTypes: ['Strawberries', 'Watermelons', 'Melons', 'Cucumbers'],
    ratings: 4.4,
  },
  {
    id: 'farmer-7',
    name: 'Hassan Chakir',
    email: 'hassan.chakir@farm.ma',
    role: 'farmer',
    avatar: 'https://i.pravatar.cc/150?img=13',
    phoneNumber: '+212607080910',
    address: 'Beni Mellal, Beni Mellal-Khenifra',
    createdAt: new Date('2023-03-15'),
    farmName: 'Tadla Plains Agriculture',
    farmLocation: {
      latitude: 32.3373,
      longitude: -6.3498,
      address: 'Beni Mellal, Beni Mellal-Khenifra',
    },
    cropTypes: ['Wheat', 'Barley', 'Corn', 'Sunflowers'],
    ratings: 4.3,
  },
  {
    id: 'farmer-8',
    name: 'Nadia Berrada',
    email: 'nadia.berrada@farm.ma',
    role: 'farmer',
    avatar: 'https://i.pravatar.cc/150?img=15',
    phoneNumber: '+212608091011',
    address: 'Agadir, Souss-Massa',
    createdAt: new Date('2023-01-08'),
    farmName: 'Souss Export Farm',
    farmLocation: {
      latitude: 30.4278,
      longitude: -9.5981,
      address: 'Agadir, Souss-Massa',
    },
    cropTypes: ['Tomatoes', 'Peppers', 'Zucchini', 'Eggplants'],
    ratings: 4.9,
  }
];

// Demo Transport Agencies Data
const demoTransporters: Transporter[] = [
  {
    id: 'transport-1',
    name: 'Mohammed Fassi',
    email: 'mohammed.fassi@transport.ma',
    role: 'transporter',
    avatar: 'https://i.pravatar.cc/150?img=2',
    phoneNumber: '+212661020304',
    address: 'Zone Industrielle, Casablanca',
    createdAt: new Date('2023-02-20'),
    companyName: 'FastMove Logistics',
    baseLocation: {
      latitude: 33.5731,
      longitude: -7.5898,
      address: 'Zone Industrielle, Casablanca',
    },
    ratings: 4.5,
  },
  {
    id: 'transport-2',
    name: 'Rachid Alaoui',
    email: 'rachid.alaoui@transport.ma',
    role: 'transporter',
    avatar: 'https://i.pravatar.cc/150?img=4',
    phoneNumber: '+212662030405',
    address: 'Quartier Industriel, Rabat',
    createdAt: new Date('2023-01-25'),
    companyName: 'Atlas Transport Solutions',
    baseLocation: {
      latitude: 34.0209,
      longitude: -6.8417,
      address: 'Quartier Industriel, Rabat',
    },
    ratings: 4.7,
  },
  {
    id: 'transport-3',
    name: 'Laila Benjelloun',
    email: 'laila.benjelloun@transport.ma',
    role: 'transporter',
    avatar: 'https://i.pravatar.cc/150?img=6',
    phoneNumber: '+212663040506',
    address: 'Zone Logistique, Tangier',
    createdAt: new Date('2023-03-10'),
    companyName: 'Mediterranean Freight',
    baseLocation: {
      latitude: 35.7595,
      longitude: -5.8340,
      address: 'Zone Logistique, Tangier',
    },
    ratings: 4.6,
  },
  {
    id: 'transport-4',
    name: 'Abdelkader Senhaji',
    email: 'abdelkader.senhaji@transport.ma',
    role: 'transporter',
    avatar: 'https://i.pravatar.cc/150?img=8',
    phoneNumber: '+212664050607',
    address: 'Quartier Al Massira, Agadir',
    createdAt: new Date('2023-02-15'),
    companyName: 'Souss Express',
    baseLocation: {
      latitude: 30.4278,
      longitude: -9.5981,
      address: 'Quartier Al Massira, Agadir',
    },
    ratings: 4.8,
  },
  {
    id: 'transport-5',
    name: 'Samira Tounsi',
    email: 'samira.tounsi@transport.ma',
    role: 'transporter',
    avatar: 'https://i.pravatar.cc/150?img=10',
    phoneNumber: '+212665060708',
    address: 'Zone Industrielle, Fes',
    createdAt: new Date('2023-04-05'),
    companyName: 'Imperial Transport',
    baseLocation: {
      latitude: 34.0181,
      longitude: -5.0078,
      address: 'Zone Industrielle, Fes',
    },
    ratings: 4.4,
  },
  {
    id: 'transport-6',
    name: 'Khalid Benali',
    email: 'khalid.benali@transport.ma',
    role: 'transporter',
    avatar: 'https://i.pravatar.cc/150?img=12',
    phoneNumber: '+212666070809',
    address: 'Port Area, Kenitra',
    createdAt: new Date('2023-01-30'),
    companyName: 'Atlantic Cargo',
    baseLocation: {
      latitude: 34.2610,
      longitude: -6.5802,
      address: 'Port Area, Kenitra',
    },
    ratings: 4.3,
  }
];

// Demo Stores/Clients Data
const demoStores: Store[] = [
  {
    id: 'store-1',
    name: 'Marjane Holding',
    email: 'procurement@marjane.ma',
    role: 'store',
    avatar: 'https://i.pravatar.cc/150?img=16',
    phoneNumber: '+212520304050',
    address: 'Marjane Californie, Casablanca',
    createdAt: new Date('2023-01-10'),
    storeName: 'Marjane Californie',
    storeLocation: {
      latitude: 33.5731,
      longitude: -7.5898,
      address: 'Marjane Californie, Casablanca',
    },
    storeType: 'supermarket',
    businessLicense: 'SUP-2023-001',
    preferredProducts: ['Fruits', 'Vegetables', 'Dairy', 'Grains'],
    ratings: 4.6,
    operatingHours: {
      open: '08:00',
      close: '22:00',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
    }
  },
  {
    id: 'store-2',
    name: 'Carrefour Market',
    email: 'supply@carrefour.ma',
    role: 'store',
    avatar: 'https://i.pravatar.cc/150?img=17',
    phoneNumber: '+212521304051',
    address: 'Carrefour Rabat, Rabat',
    createdAt: new Date('2023-01-15'),
    storeName: 'Carrefour Rabat',
    storeLocation: {
      latitude: 34.0209,
      longitude: -6.8417,
      address: 'Carrefour Rabat, Rabat',
    },
    storeType: 'supermarket',
    businessLicense: 'SUP-2023-002',
    preferredProducts: ['Fresh Produce', 'Organic Foods', 'Meat', 'Seafood'],
    ratings: 4.5,
    operatingHours: {
      open: '09:00',
      close: '21:00',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
    }
  },
  {
    id: 'store-3',
    name: 'Restaurant La Mamounia',
    email: 'chef@lamamounia.ma',
    role: 'store',
    avatar: 'https://i.pravatar.cc/150?img=18',
    phoneNumber: '+212522304052',
    address: 'Avenue Bab Jdid, Marrakech',
    createdAt: new Date('2023-02-01'),
    storeName: 'La Mamounia Restaurant',
    storeLocation: {
      latitude: 31.6295,
      longitude: -7.9811,
      address: 'Avenue Bab Jdid, Marrakech',
    },
    storeType: 'restaurant',
    businessLicense: 'REST-2023-001',
    preferredProducts: ['Premium Vegetables', 'Fresh Herbs', 'Organic Fruits', 'Specialty Items'],
    ratings: 4.9,
    operatingHours: {
      open: '19:00',
      close: '23:00',
      days: ['Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
    }
  },
  {
    id: 'store-4',
    name: 'Metro Cash & Carry',
    email: 'wholesale@metro.ma',
    role: 'store',
    avatar: 'https://i.pravatar.cc/150?img=19',
    phoneNumber: '+212523304053',
    address: 'Zone Industrielle Ain Sebaa, Casablanca',
    createdAt: new Date('2023-02-10'),
    storeName: 'Metro Ain Sebaa',
    storeLocation: {
      latitude: 33.6178,
      longitude: -7.5266,
      address: 'Zone Industrielle Ain Sebaa, Casablanca',
    },
    storeType: 'wholesaler',
    businessLicense: 'WHO-2023-001',
    preferredProducts: ['Bulk Vegetables', 'Bulk Fruits', 'Grains', 'Processed Foods'],
    ratings: 4.4,
    operatingHours: {
      open: '06:00',
      close: '18:00',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
    }
  },
  {
    id: 'store-5',
    name: 'BIM Discount',
    email: 'purchasing@bim.ma',
    role: 'store',
    avatar: 'https://i.pravatar.cc/150?img=20',
    phoneNumber: '+212524304054',
    address: 'Hay Mohammadi, Agadir',
    createdAt: new Date('2023-02-20'),
    storeName: 'BIM Agadir',
    storeLocation: {
      latitude: 30.4278,
      longitude: -9.5981,
      address: 'Hay Mohammadi, Agadir',
    },
    storeType: 'retailer',
    businessLicense: 'RET-2023-001',
    preferredProducts: ['Budget Fruits', 'Basic Vegetables', 'Staple Foods'],
    ratings: 4.2,
    operatingHours: {
      open: '08:00',
      close: '20:00',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
    }
  },
  {
    id: 'store-6',
    name: 'Aswak Assalam',
    email: 'procurement@aswakassalam.ma',
    role: 'store',
    avatar: 'https://i.pravatar.cc/150?img=21',
    phoneNumber: '+212525304055',
    address: 'Boulevard Zerktouni, Casablanca',
    createdAt: new Date('2023-03-01'),
    storeName: 'Aswak Assalam Zerktouni',
    storeLocation: {
      latitude: 33.5892,
      longitude: -7.6261,
      address: 'Boulevard Zerktouni, Casablanca',
    },
    storeType: 'supermarket',
    businessLicense: 'SUP-2023-003',
    preferredProducts: ['Local Produce', 'Traditional Foods', 'Fresh Meat', 'Dairy'],
    ratings: 4.3,
    operatingHours: {
      open: '08:30',
      close: '21:30',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
    }
  },
  {
    id: 'store-7',
    name: 'Restaurant Rick\'s Café',
    email: 'kitchen@rickscafe.ma',
    role: 'store',
    avatar: 'https://i.pravatar.cc/150?img=22',
    phoneNumber: '+212526304056',
    address: 'Place du Jardin Public, Casablanca',
    createdAt: new Date('2023-03-10'),
    storeName: 'Rick\'s Café',
    storeLocation: {
      latitude: 33.5731,
      longitude: -7.5898,
      address: 'Place du Jardin Public, Casablanca',
    },
    storeType: 'restaurant',
    businessLicense: 'REST-2023-002',
    preferredProducts: ['Premium Seafood', 'Fresh Vegetables', 'Exotic Fruits', 'Herbs'],
    ratings: 4.7,
    operatingHours: {
      open: '18:00',
      close: '01:00',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
    }
  },
  {
    id: 'store-8',
    name: 'Conserverie Aicha',
    email: 'sourcing@aicha.ma',
    role: 'store',
    avatar: 'https://i.pravatar.cc/150?img=23',
    phoneNumber: '+212527304057',
    address: 'Zone Industrielle, El Jadida',
    createdAt: new Date('2023-03-15'),
    storeName: 'Aicha Processing Plant',
    storeLocation: {
      latitude: 33.2316,
      longitude: -8.5007,
      address: 'Zone Industrielle, El Jadida',
    },
    storeType: 'processor',
    businessLicense: 'PRO-2023-001',
    preferredProducts: ['Tomatoes', 'Peppers', 'Olives', 'Citrus Fruits'],
    ratings: 4.5,
    operatingHours: {
      open: '07:00',
      close: '17:00',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
    }
  }
];

// Demo Vehicles Data
const demoVehicles: Vehicle[] = [
  {
    id: 'vehicle-1',
    type: 'truck',
    licensePlate: '123456-A-17',
    capacity: 10,
    isRefrigerated: true,
    isAvailable: true,
    currentLocation: {
      latitude: 33.5731,
      longitude: -7.5898,
      address: 'Casablanca, Morocco',
    },
    driver: {
      name: 'Hassan Alami',
      phoneNumber: '+212661234567',
    },
  },
  {
    id: 'vehicle-2',
    type: 'van',
    licensePlate: '789012-B-06',
    capacity: 3,
    isRefrigerated: false,
    isAvailable: true,
    currentLocation: {
      latitude: 34.0209,
      longitude: -6.8417,
      address: 'Rabat, Morocco',
    },
    driver: {
      name: 'Youssef Benali',
      phoneNumber: '+212662345678',
    },
  },
  {
    id: 'vehicle-3',
    type: 'refrigerated',
    licensePlate: '345678-C-12',
    capacity: 8,
    isRefrigerated: true,
    isAvailable: false,
    currentLocation: {
      latitude: 30.4278,
      longitude: -9.5981,
      address: 'Agadir, Morocco',
    },
    driver: {
      name: 'Fatima Zahra',
      phoneNumber: '+212663456789',
    },
  },
  {
    id: 'vehicle-4',
    type: 'pickup',
    licensePlate: '901234-D-33',
    capacity: 1.5,
    isRefrigerated: false,
    isAvailable: true,
    currentLocation: {
      latitude: 31.6295,
      longitude: -7.9811,
      address: 'Marrakech, Morocco',
    },
    driver: {
      name: 'Ahmed Tazi',
      phoneNumber: '+212664567890',
    },
  },
  {
    id: 'vehicle-5',
    type: 'truck',
    licensePlate: '567890-E-09',
    capacity: 15,
    isRefrigerated: false,
    isAvailable: true,
    currentLocation: {
      latitude: 35.7595,
      longitude: -5.8340,
      address: 'Tangier, Morocco',
    },
    driver: {
      name: 'Rachid Fassi',
      phoneNumber: '+212665678901',
    },
  },
];

// Demo Marketplace Listings
const demoMarketplaceListings: MarketplaceListing[] = [
  {
    id: 'listing-1',
    farmerId: 'farmer-1',
    typeOfGood: 'Oranges',
    condition: 'Fresh',
    quantity: 500,
    unit: 'kg',
    quality: 'Grade A',
    timeOfOffer: new Date('2025-08-10T08:00:00'),
    location: 'Marrakech',
    photos: ['https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=300'],
    pricePerUnit: 8,
    deliveryOptions: ['FastMove Logistics', 'Atlas Transport Solutions'],
    status: 'available',
  },
  {
    id: 'listing-2',
    farmerId: 'farmer-2',
    typeOfGood: 'Strawberries',
    condition: 'Organic',
    quantity: 200,
    unit: 'kg',
    quality: 'Premium',
    timeOfOffer: new Date('2025-08-09T14:30:00'),
    location: 'Casablanca',
    photos: ['https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=300'],
    pricePerUnit: 25,
    deliveryOptions: ['Mediterranean Freight'],
    status: 'available',
  },
  {
    id: 'listing-3',
    farmerId: 'farmer-3',
    typeOfGood: 'Lemons',
    condition: 'Fresh',
    quantity: 800,
    unit: 'kg',
    quality: 'Grade A',
    timeOfOffer: new Date('2025-08-08T10:15:00'),
    location: 'Taroudant',
    photos: ['https://images.unsplash.com/photo-1590502593747-42a996133562?w=300'],
    pricePerUnit: 6,
    deliveryOptions: ['Souss Express', 'FastMove Logistics'],
    status: 'available',
  },
  {
    id: 'listing-4',
    farmerId: 'farmer-4',
    typeOfGood: 'Potatoes',
    condition: 'Fresh',
    quantity: 1000,
    unit: 'kg',
    quality: 'Grade B',
    timeOfOffer: new Date('2025-08-07T16:45:00'),
    location: 'Fes',
    photos: ['https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=300'],
    pricePerUnit: 4,
    deliveryOptions: ['Imperial Transport', 'Atlantic Cargo'],
    status: 'available',
  },
  {
    id: 'listing-5',
    farmerId: 'farmer-5',
    typeOfGood: 'Clementines',
    condition: 'Fresh',
    quantity: 600,
    unit: 'kg',
    quality: 'Premium',
    timeOfOffer: new Date('2025-08-06T12:20:00'),
    location: 'Berkane',
    photos: ['https://images.unsplash.com/photo-1577234286642-fc512a5f8f11?w=300'],
    pricePerUnit: 12,
    deliveryOptions: ['Mediterranean Freight'],
    status: 'sold',
  },
];

export const useDemoDataStore = create<DemoDataState>(() => ({
  farmers: demoFarmers,
  transporters: demoTransporters,
  stores: demoStores,
  vehicles: demoVehicles,
  marketplaceListings: demoMarketplaceListings,
  transportRequests: [],
}));
